name: Daily Commit
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Configure Git
        run: |
          git config user.name "smith-gayen"
          git config user.email "YOUR_ID+smith-gayen@users.noreply.github.com"

      - name: Make a daily commit
        run: |
          date > date.txt
          git add date.txt
          git commit -m "Automated commit on $(date)"
          git push
